spring:
  application:
    name: APIGATEWAY-SERVICE
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes:
        - id: operation-service
          uri: lb://OPERATION-SERVICE
          predicates:
            - Path=/hotel/**

        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/booking/**
        

server:
  port: 9898

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: hystrix.stream


